console.log(" welcome to  devops  demoshowcase v4")
console.log(" welcome to  devops  presentation 3")
console.log("2nd phase presentation")
console.log("3rd phase presentation")
console.log("5th phase presentation")
